#!/bin/bash
set -e

ARCH=${ARCH:-"amd64"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p dist/artifacts rootfs
cd rootfs

mkdir -p \
usr/bin \
usr/local/etc/strongswan.d

tar xvfz ../strongswan/strongswan*.tar.gz
cp ../package/charon.conf usr/local/etc/strongswan.d/charon.conf
cp ../package/start-ipsec.sh usr/bin/start-ipsec.sh
cp ../bin/rancher-ipsec usr/bin/rancher-ipsec

tar cvzf ../dist/artifacts/rancher-ipsec-${ARCH}-${VERSION}.tar.gz .

echo "Built rancher-ipsec-${ARCH}-${VERSION}.tar.gz"
